services:
  app:
    image: app
    build: .
    ports:
      - "3000:3000"
    env_file: "./.env"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example